name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    types: [opened, synchronize]

jobs:
  test-build:
    name: Test and building
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 8.6.6

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Building
        run: pnpm build
        env:
          DATABASE_URL: "https://localhost.com"
          NEXTAUTH_URL: "https://localhost.com"
          NEXTAUTH_SECRET: "abc123"
          DISCORD_CLIENT_ID: "abc123"
          DISCORD_CLIENT_SECRET: "abc123"

      - name: Linting
        run: pnpm lint
        env:
          DATABASE_URL: "https://localhost.com"
          NEXTAUTH_URL: "https://localhost.com"
          NEXTAUTH_SECRET: "abc123"
          DISCORD_CLIENT_ID: "abc123"
          DISCORD_CLIENT_SECRET: "abc123"

      - name: Type-checking
        run: pnpm type-check
